#ifndef CSE332_LAB4_H
#define CSE332_LAB4_H

#include <string>
#include <iostream>

#include <stdio.h>
#include <stdint.h>

// defining a few constants
#define DEBUG 0

#define NULL_CHAR "\0"
#define FIVE 5
#define FOUR 4
#define THREE 3
#define TWO 2
#define ONE 1
#define ZERO 0
#define MAX_NUMBER_OF_ARGS	3
#define NUMBER_OF_MSG	2
#define PROG_NAME 0
#define ARG_ONE 1
#define ARG_TWO 2
#define NUM_MSG 4
#define DECK_SIZE 52
#define HAND_SIZE 5
#define INIT_NUM_CHIPS 20

typedef enum {
	STRAIGHTFLUSH = 800, FOUR_OF_KIND = 799, FULL_HOUSE = 798, FLUSH = 797,
	STRAIGHT = 796, THREE_OF_KIND = 795, TWO_PAIRS = 794, ONE_PAIR = 793,
	NO_RANK = 792, HAND_ERROR = -800
}hand_enum;

enum RETURN_VALUE {
	SUCCESS = 0, UNABLE_TO_OPEN_FILE = 101,
	UNABLE_TO_READ_FILE = 102, UNABLE_TO_EXECUTE = 103, ONLY_SHUFFLE_ARGS = 104,
	NO_SHUFFLE_ARGS = 105, NO_ARGS = 106, TOO_MANY_ARGS = 107, TOO_FEW_ARGS = 108,
	UNKNOWN_INPUT_ARGS = 109, TOO_FEW_CARD_DECK = 110, MAIN_DECK_AND_DISC_DECK_EMPTY = 111,
	DISCARD_DECK_NOT_EMPTY = 112, PLAYER_HAND_NOT_EMPTY = 113, CARDS_MAIN_DECK_NOT_52 = 114,
	WRONG_GAME_NAME = 115, UNKNOWN_EXCEPTION = -11111111
};

typedef enum {
	HANDS_SIZE_NOT_EQUAL = 500, EXEC_STRAIGHT_FLUSH_HAND = 501,
	EXEC_FOUR_OF_KIND_HAND = 502, EXEC_FULL_HOUSE_HAND = 503, EXEC_FLUSH_HAND = 504,
	EXEC_STRAIGHT_HAND = 505, EXEC_THREE_OF_KIND_HAND = 506, EXEC_TWO_PAIRS_HAND = 507,
	EXEC_ONE_PAIRS_HAND = 508, EXEC_NO_RANK_HAND = 509, POS_GREATER_THAN_SIZE = 510,
	UNKOWN_RANK = 511
} hand_exc_t;

typedef enum {
	DECK_CARD_INSERT_ERROR = 1000
}deck_exec_t;

typedef enum {
	INSTANCE_NOT_AVAILABLE = 10000, GAME_ALREADY_STARTED = 10001,
	NO_GAME_IN_PROGRESS = 10002, ALREADY_PLAYING = 10003, PLAYER_CHIPS_NUM_NOT_VALID = 10004,
	UNKNOWN_GAME = 11111
} game_exec_t;

enum MSG_NUMBER {
	MSG_ONE = 1, MSG_TWO = 2, MSG_THREE = 3,
	MSG_FOUR = 4, MSG_FIVE = 5, MSG_SIX = 6
};


int PrintUsage(char * prog_name, std::string err_msg, int err);

#endif // CSE332_LAB2_H

